"""
Django settings for SmartStudy_website project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-psu@sh#f!&v#2n&44a=^%d)#n&ms0!kncs03zu9vc&tv+#a)(a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'SSApp',
    'social_django',
    'rest_framework',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]

SOCIAL_AUTH_PIPELINE = [
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
]

ROOT_URLCONF = 'SmartStudy_website.urls'

CSRF_TRUSTED_ORIGINS = []

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'SmartStudy_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 25,
        }
    }
}

REST_FRAMEWORK = {
    # cài đặt trang api, mỗi giới hạn data - hiện ra mỗi trang
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination', 
                                #'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,  # Số lượng dữ liệu hiển thị mỗi trang (mặc định là 100)
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/upload/'
MEDIA_ROOT = '%s/SSApp/static/upload/' %BASE_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#authentication
AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    "django.contrib.auth.backends.ModelBackend",
]

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_URL = "logout"
LOGOUT_REDIRECT_URL = "login"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "1052919731334-b0eh2o5grbkkoj2h400q5eh9b4kp54j6.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"

# SOCIAL_AUTH_LOGIN_ERROR_URL = 'register'
# SOCIAL_AUTH_BACKEND_ERROR_URL = 'register'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = "smartstudy2023edu@gmail.com"
EMAIL_HOST_PASSWORD = "zmnx nlsd yvvn ciyh"

# TOKEN API 
GENAI_KEYS = [
    "AIzaSyB6VIzIMt-Eax92Zt9GPQeiM0wE2KLo090", 
    "AIzaSyBsDUsHnMcr_Ge2v_bfUqHM93UyxQhhLoM",
    "AIzaSyDa6lrPCSEBRNCSdf9rNT7fB-M0LtUauSk",
    "AIzaSyCviosQe-qIKt_MhseTVXO7GEYzmCkVSmE",
    "AIzaSyBLi2riLSjuQEfnyIf31aoSlEJNluq8-F4", 
    # "AIzaSyAn0P7Dlsr9ECtxIAXF8t7HsLEIwZsv12w",
    # "AIzaSyBurZlgp1HygtPZxR-VwOxgr_2HZZQKo1U",
    # "AIzaSyAHQeP6Kxts5kx8IftP-EShNb9P9a18uGM",
] # len = 5

OPENAI_KEY = ""

GITHUB_KEY = "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"
# GITHUB_KEY = 

