# Generated by Django 5.0.3 on 2024-05-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverer', models.CharField(blank=True, max_length=100, null=True)),
                ('name_of_chemical', models.CharField(max_length=100)),
                ('symbol_chemical', models.CharField(max_length=5)),
                ('plase', models.CharField(max_length=10)),
                ('category', models.TextField()),
                ('block', models.CharField(max_length=2)),
                ('period', models.IntegerField()),
                ('group', models.CharField(max_length=5)),
                ('configuration', models.TextField()),
                ('electronegativity', models.FloatField(blank=True)),
                ('oxidation', models.TextField(blank=True, null=True)),
                ('atomic_mass', models.FloatField()),
                ('density', models.FloatField(blank=True, null=True)),
                ('boil_K', models.FloatField(blank=True, null=True)),
                ('melt_K', models.FloatField(blank=True, null=True)),
                ('appearance', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('image_URL', models.TextField()),
                ('classify', models.CharField(max_length=15)),
                ('other_classification', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eng_Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('mean', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Irregular_Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb1', models.CharField(max_length=20)),
                ('verb2', models.CharField(max_length=50)),
                ('verb3', models.CharField(max_length=50)),
                ('mean', models.TextField()),
            ],
        ),
    ]
