# Generated by Django 5.0.3 on 2024-05-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_File_PDF', models.FileField(blank=True, upload_to='upload/files/pdf/')),
                ('_File_word', models.FileField(blank=True, upload_to='upload/files/rar/')),
                ('image', models.ImageField(blank=True, upload_to='upload/images/')),
                ('content', models.CharField(max_length=150)),
                ('_class', models.IntegerField()),
                ('semester', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='SSApp.category')),
            ],
        ),
    ]
