# Generated by Django 5.0.3 on 2024-06-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSApp', '0003_userid_fb_vieword_alter_exam__file_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='_File_PDF',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='_File_word',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='image',
        ),
        migrations.AddField(
            model_name='exam',
            name='URL_File_word',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='URL_PDF',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='URL_image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='path_reder',
            field=models.TextField(default=''),
        ),
    ]
