# Generated by Django 5.0.3 on 2024-06-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSApp', '0004_remove_exam__file_pdf_remove_exam__file_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='path_reder',
            new_name='content_path',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='_class',
            new_name='exam_class',
        ),
        migrations.AddField(
            model_name='exam',
            name='path_render',
            field=models.TextField(default=''),
        ),
    ]
